[package]
edition = "2021"
name = "cxx-auto"
version = "0.0.3"
authors = ["silvanshade <silvanshade@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/silvanshade/cxx-auto"
documentation = "https://silvanshade.github.io/cxx-auto/cxx_auto"
description = "Automatically generate cxx bindings"
# NOTE: `links` is needed so that `cxx/include/**/*.hxx` is exported to dependencies
links = "cxx-auto"

[features]
bytemuck = ["dep:bytemuck"]

[build-dependencies]
cxx-build = { version = "1.0", default-features = false, features = ["parallel"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dependencies]
bytemuck = { version = "1.13", optional = true, default-features = false, features = ["derive"] }
cxx = { version = "1.0", default-features = false, features = ["c++20", "std"] }
cxx-build = { version = "1.0", default-features = false, features = ["parallel"] }
indexmap = { version = "2.0", default-features = false, features = ["serde"] }
libc = { version = "0.2", default-features = false }
moveref = { version = "0.0", default-features = false }
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }
rust-format = { version = "0.3", default-features = false, features = ["token_stream"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["preserve_order"] }
static_assertions = { version = "1.1", default-features = false }
syn = { version = "2.0", default-features = false }
walkdir = { version = "2.3", default-features = false }

# [patch.crates-io]
# moveref = { path = "../moveref" }
