[package]
edition = "2021"
name = "cxx-auto"
version = "0.0.0"
authors = ["silvanshade <silvanshade@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/silvanshade/cxx-auto"
documentation = "https://silvanshade.github.io/cxx-auto/cxx_auto"
description = "Automatically generate cxx bindings"
readme = "../README.md"
categories = ["api-bindings", "compilers", "development-tools", "external-ffi-bindings", "rust-patterns"]
keywords = ["cxx", "c++", "clang", "gcc", "ffi", "codegen", "binding"]
links = "cxx-auto"

[features]
bytemuck = ["dep:bytemuck"]
ctypes = ["dep:libc", "stabby?/libc"]
stabby = ["dep:stabby"]
std = ["stabby?/std"]

[build-dependencies]
cxx-build.workspace = true

[dependencies]
bytemuck = { version = "1.13", optional = true, default-features = false, features = ["derive"] }
libc = { version = "0.2", optional = true, default-features = false }
moveref = { version = "0.0", default-features = false }
stabby = { version = "5.0", optional = true, default-features = false }
static_assertions = { version = "1.1", default-features = false }

# [patch.crates-io]
# moveref = { path = "../moveref" }
