use indexmap::IndexMap;

#[allow(clippy::exhaustive_structs, clippy::struct_excessive_bools)]
pub struct TypeElab {
    pub path_components: Vec<&'static str>,
    pub path_descendants: Vec<&'static str>,
    pub cxx_include: &'static str,
    pub cxx_namespace: &'static str,
    pub cxx_name: &'static str,
    pub rust_name: &'static str,
    pub rust_lifetimes: IndexMap<&'static str, Vec<&'static str>>,
    pub cxx_abi_align: usize,
    pub cxx_abi_size: usize,
    pub cxx_has_operator_equal: bool,
    pub cxx_has_operator_not_equal: bool,
    pub cxx_has_operator_less_than: bool,
    pub cxx_has_operator_less_than_or_equal: bool,
    pub cxx_has_operator_greater_than: bool,
    pub cxx_has_operator_greater_than_or_equal: bool,
    pub is_rust_cxx_extern_type_trivial: bool,
    pub is_rust_unpin: bool,
    pub is_rust_send: bool,
    pub is_rust_sync: bool,
    pub is_rust_copy: bool,
    pub is_rust_debug: bool,
    pub is_rust_default: bool,
    pub is_rust_display: bool,
    pub is_rust_drop: bool,
    pub is_rust_copy_new: bool,
    pub is_rust_move_new: bool,
    pub is_rust_eq: bool,
    pub is_rust_partial_eq: bool,
    pub is_rust_partial_ord: bool,
    pub is_rust_ord: bool,
    pub is_rust_hash: bool,
}
